{% set name = "pyinstaller-hooks-contrib" %}
{% set version = "2022.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/v{{ version }}.tar.gz
  sha256: 6e03bfa2e6f7056e809ea837e1feaa77c4f6fe3e17bb45db4b601caac109766c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - _pyinstaller_hooks_contrib
    - _pyinstaller_hooks_contrib.hooks

about:
  home: https://github.com/pyinstaller/pyinstaller-hooks-contrib
  summary: Community maintained hooks for PyInstaller
  license: Apache-2.0 OR GPL-2.0-or-later
  license_file:
    - LICENSE.GPL.txt
    - LICENSE.APL.txt
  description: |
    A "hook" file extends PyInstaller to adapt it to the special needs and
    methods used by a Python package. The word "hook" is used for two kinds of
    files. A runtime hook helps the bootloader to launch an app, setting up the
    environment. A package hook (there are several types of those) tells
    PyInstaller what to include in the final app - such as the data files and
    (hidden) imports mentioned above.
  doc_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/wiki
  dev_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib

extra:
  recipe-maintainers:
    - nehaljwani
